### ISSUE TITLE
Failure scan

### ISSUE THREAD

**Issue by Cykucjusz** [serphacker/serposcope#132]
@serphacker 
proxy:direct try 1
[2016-09-29 08:23:13,538] [google-0] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
[2016-09-29 08:23:13,538] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:direct
[2016-09-29 08:23:13,852] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - invalid captcha form
[2016-09-29 08:23:13,852] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.pl/search?q=QUERY&num=100 via proxy:direct try 2
[2016-09-29 08:23:14,311] [google-0] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
[2016-09-29 08:23:14,311] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:direct
[2016-09-29 08:23:14,569] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - invalid captcha form
[2016-09-29 08:23:14,569] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.pl/search?q=QUERY&num=100 via proxy:direct try 3
[2016-09-29 08:23:15,097] [google-0] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]

**Comment by pp-1** [comment]
Same here:

`[2016-09-29 11:01:29,404] [Thread-176] WARN  c.s.s.t.g.GoogleTask - no proxy configured, using direct connection
[2016-09-29 11:01:29,406] [google-0] INFO  c.s.s.t.g.GoogleTaskRunnable - google thread started
[2016-09-29 11:01:29,407] [google-0] INFO  c.s.s.t.g.GoogleTaskRunnable - search "OBF" | try 1 | total search done : 0/299
[2016-09-29 11:01:29,407] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.pl/search?q=#OBF#search-99#&num=30 via proxy:direct try 1
[2016-09-29 11:01:29,876] [google-0] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
[2016-09-29 11:01:29,876] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:direct
[2016-09-29 11:01:29,975] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - invalid captcha form
[2016-09-29 11:01:29,976] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.pl/search?q=#OBF#search-99#&num=30 via proxy:direct try 2
[2016-09-29 11:01:30,323] [google-0] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
[2016-09-29 11:01:30,323] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:direct
[2016-09-29 11:01:31,068] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - invalid captcha form
[2016-09-29 11:01:31,069] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.pl/search?q=#OBF#search-99#&num=30 via proxy:direct try 3
[2016-09-29 11:01:31,431] [google-0] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
[2016-09-29 11:01:31,432] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:direct
[2016-09-29 11:01:31,464] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - invalid captcha form
[2016-09-29 11:01:31,473] [google-0] WARN  c.s.s.t.g.GoogleTaskRunnable - scrap failed for OBF because of ERROR_NETWORK
[2016-09-29 11:01:31,473] [google-0] WARN  c.s.s.t.g.GoogleTaskRunnable - no more proxy, stopping the thread
[2016-09-29 11:01:31,473] [google-0] INFO  c.s.s.t.g.GoogleTaskRunnable - google thread stopped`

I have configured DeathByCaptcha and Anti-Captcha, but basing on DBC stats, it seems Serposcope doesn't even query for captcha solving.
This issue appeared today, yesterday's check went ok.

**Comment by serphacker** [comment]
Google may have changed something on its captcha form, I check that today

**Comment by serphacker** [comment]
fixed, I publish new version ASAP

**Comment by Cykucjusz** [comment]
@serphacker God will reward you..

**Comment by serphacker** [comment]
2.6 including the fix have been released

**Comment by Quinty11** [comment]
I still see version 2.5.1 in the right upper corner, how do i update?

**Comment by serphacker** [comment]
download the latest version on serposcope.serphacker.com and install it, it won't autoupdate itself.

**Comment by Quinty11** [comment]
aahh ok, i will not loose any data?

**Comment by serphacker** [comment]
you won't lose any data
