### ISSUE TITLE
Can't find captcha img tag

### ISSUE THREAD

**Issue by Cykucjusz** [serphacker/serposcope#155]
@serphacker 
> [2017-03-13 21:26:50,456] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.pl/search?q=Cykucjusz.pl&num=200 via proxy:direct try 3
> [2017-03-13 21:26:50,983] [google-0] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
> [2017-03-13 21:26:50,983] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:direct
> [2017-03-13 21:26:51,097] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - can't find captcha img tag
> [2017-03-13 21:26:51,098] [google-0] WARN  c.s.s.t.g.GoogleTaskRunnable - scrap failed for Cykucjusz.pl because of ERROR_NETWORK
> [2017-03-13 21:26:51,098] [google-0] WARN  c.s.s.t.g.GoogleTaskRunnable - no more proxy, stopping the thread
> [2017-03-13 21:26:51,099] [google-0] INFO  c.s.s.t.g.GoogleTaskRunnable - google thread stopped
> [2017-03-13 21:26:51,105] [Thread-23] WARN  c.s.s.t.g.GoogleTask - 1 proxies failed during the task
> [2017-03-13 21:26:51,106] [Thread-23] WARN  c.s.s.t.g.GoogleTask - 192 searches have not been checked
> [2017-03-13 21:26:51,107] [Thread-23] INFO  c.s.s.t.AbstractTask - task done for module GOOGLE

Cant't scan serp for [Cykucjusz.pl](https://Cykucjusz.pl/) because can't find captcha img tag with c.s.s.s.g.s.GoogleScraper

**Comment by serphacker** [comment]
Hello, I did notice this log message in some serposcope setup but I didn't manage to reproduce it.

Nevertheless, it seems to only trigger when you are doing too many request and too fast to google with the same IP. It probably means your proxy is temporary blacklisted.

The fix is to increase pause, and reduce the number of thread.

**Comment by serphacker** [comment]
I did manage to reproduce the issue. 

Google is now using recaptcha for the captcha instead of the standard captcha hence it is not recognized by serposcope.

It is a big issue which need to be fixed

**Comment by Cykucjusz** [comment]
@serphacker 
On captcha form there is old noscript Captcha img and Recaptcha div
You can choose old Captcha img by disabling js

**Comment by serphacker** [comment]
No, not on the new captcha form. Currently Google is using both old form (with noscript) and a new form (recaptcha only). On the long term there will be only new form.

**Comment by LeFrenchie** [comment]
Pierre, have you a deadline for this fix ?  thx

**Comment by serphacker** [comment]
The fix is small, but I'm very busy now. It will be fixed in a few days.

**Comment by mit686** [comment]
@serphacker same thing here, I can't use Serposcope after this new Google update.

**Comment by mit686** [comment]
@serphacker thank you, testing out right now

**Comment by serphacker** [comment]
Guys i'll publish a link to a beta version including the fix on this thread ASAP stay tunned.

**Comment by serphacker** [comment]
So I published a beta build for Linux (debian) or the universal jar here : 
https://serposcope.serphacker.com/beta/2.7.0/

Unfortunately I didn't have the time to make a build for Windows, you'll have to wait a few days more.

You will need to have an account because support for Decaptcher and DeathByCaptcha have been dropped.

Please tell me if it works ok so I can release the final version ASAP.

**Comment by serphacker** [comment]
I managed somehow to make the Windows build too.

**Comment by Cykucjusz** [comment]
> Please tell me if it works ok so I can release the final version ASAP.
I must wait few days for Pay-Pal-->Anti-Captcha transfer. I will inform You about new version ASAP.

**Comment by mit686** [comment]
@Cykucjusz I tested new beta. It works fine!
@serphacker Thank you so much!

**Comment by zordon32** [comment]
Still having issues:

[2017-03-16 09:13:20,305] [google-7] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:http://37.48.118.90:13040/
[2017-03-16 09:13:27,135] [google-7] DEBUG c.s.s.s.g.s.GoogleScraper - trying with captcha recaptcha
[2017-03-16 09:13:27,136] [google-7] ERROR c.s.s.t.g.GoogleTaskRunnable - unhandled exception, aborting the thread
java.lang.NullPointerException: null
	at com.serphacker.serposcope.scraper.google.scraper.GoogleScraper.recaptchaForm(GoogleScraper.java:400) ~[serposcope.jar:na]
	at com.serphacker.serposcope.scraper.google.scraper.GoogleScraper.handleCaptchaRedirect(GoogleScraper.java:394) ~[serposcope.jar:na]
	at com.serphacker.serposcope.scraper.google.scraper.GoogleScraper.downloadSerp(GoogleScraper.java:188) ~[serposcope.jar:na]
	at com.serphacker.serposcope.scraper.google.scraper.GoogleScraper.scrap(GoogleScraper.java:99) ~[serposcope.jar:na]
	at com.serphacker.serposcope.task.google.GoogleTaskRunnable.run(GoogleTaskRunnable.java:99) ~[serposcope.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
[2017-03-16 09:13:27,137] [google-7] INFO  c.s.s.t.g.GoogleTaskRunnable - google thread stopped

**Comment by LeFrenchie** [comment]
@zordon32 is it major issue or it seems to work ? (Install in progress). thx

**Comment by serphacker** [comment]
@zordon32 @LeFrenchie I just published a new beta, tell me if it works now
https://serposcope.serphacker.com/beta/2.7.0/

**Comment by zordon32** [comment]
Sorry might have been my fault. 
I accidentally added a rotating Proxy. Deleted it and the task went 100% with no problem.
Haven't installed the new beta version yet. Will do that now.

**Comment by LeFrenchie** [comment]
It works but with anti-captcha I've some "[...] - solver can't resolve captcha (overload ?) error = SERVICE_OVERLOADED"

**Comment by serphacker** [comment]
@LeFrenchie Please provide more logs lines around this error

**Comment by LeFrenchie** [comment]
`[2017-03-16 12:23:24,012] [google-3] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.fr/search?q=----&uule=w+CAIQICIGRnJhbmNl&num=100 via proxy:http://----:80/ try 1
[2017-03-16 12:23:25,061] [google-3] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
[2017-03-16 12:23:25,061] [google-3] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:http://----:80/
[2017-03-16 12:23:25,693] [google-3] DEBUG c.s.s.s.g.s.GoogleScraper - noscript form detected, trying with captcha image
[2017-03-16 12:23:26,150] [google-3] INFO  c.s.s.s.c.s.FailoverCaptchaSolver - all captcha solver failed
[2017-03-16 12:23:26,150] [google-3] ERROR c.s.s.s.g.s.GoogleScraper - solver can't resolve captcha (overload ?) error = SERVICE_OVERLOADED
[2017-03-16 12:23:26,150] [google-3] DEBUG c.s.s.s.g.s.GoogleScraper - trying with captcha recaptcha
[2017-03-16 12:23:26,150] [google-3] INFO  c.s.s.s.c.s.FailoverCaptchaSolver - all captcha solver failed
[2017-03-16 12:23:26,150] [google-3] ERROR c.s.s.s.g.s.GoogleScraper - solver can't resolve captcha (overload ?) error = SERVICE_OVERLOADED
[2017-03-16 12:23:26,150] [google-3] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.fr/search?q=----&uule=w+CAIQICIGRnJhbmNl&num=100 via proxy:http://----:80/ try 2
[2017-03-16 12:23:26,708] [google-3] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
[2017-03-16 12:23:26,708] [google-3] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:http://----:80/
[2017-03-16 12:23:26,790] [google-3] DEBUG c.s.s.s.g.s.GoogleScraper - noscript form detected, trying with captcha image
[2017-03-16 12:23:26,945] [google-3] INFO  c.s.s.s.c.s.FailoverCaptchaSolver - all captcha solver failed
[2017-03-16 12:23:26,945] [google-3] ERROR c.s.s.s.g.s.GoogleScraper - solver can't resolve captcha (overload ?) error = SERVICE_OVERLOADED
[2017-03-16 12:23:26,945] [google-3] DEBUG c.s.s.s.g.s.GoogleScraper - trying with captcha recaptcha
[2017-03-16 12:23:26,945] [google-3] INFO  c.s.s.s.c.s.FailoverCaptchaSolver - all captcha solver failed
[2017-03-16 12:23:26,945] [google-3] ERROR c.s.s.s.g.s.GoogleScraper - solver can't resolve captcha (overload ?) error = SERVICE_OVERLOADED
[2017-03-16 12:23:26,945] [google-3] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.fr/search?q=----&uule=w+CAIQICIGRnJhbmNl&num=100 via proxy:http://----:80/ try 3
[2017-03-16 12:23:27,687] [google-3] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
[2017-03-16 12:23:27,687] [google-3] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:http://----:80/
[2017-03-16 12:23:28,003] [google-3] DEBUG c.s.s.s.g.s.GoogleScraper - noscript form detected, trying with captcha image
[2017-03-16 12:23:28,960] [google-3] INFO  c.s.s.s.c.s.FailoverCaptchaSolver - all captcha solver failed
[2017-03-16 12:23:28,960] [google-3] ERROR c.s.s.s.g.s.GoogleScraper - solver can't resolve captcha (overload ?) error = SERVICE_OVERLOADED
[2017-03-16 12:23:28,960] [google-3] DEBUG c.s.s.s.g.s.GoogleScraper - trying with captcha recaptcha
[2017-03-16 12:23:28,960] [google-3] INFO  c.s.s.s.c.s.FailoverCaptchaSolver - all captcha solver failed
[2017-03-16 12:23:28,960] [google-3] ERROR c.s.s.s.g.s.GoogleScraper - solver can't resolve captcha (overload ?) error = SERVICE_OVERLOADED
[2017-03-16 12:23:28,969] [google-3] WARN  c.s.s.t.g.GoogleTaskRunnable - scrap failed for --- because of ERROR_CAPTCHA_INCORRECT
[2017-03-16 12:23:28,969] [google-3] WARN  c.s.s.t.g.GoogleTaskRunnable - no more proxy, stopping the thread
[2017-03-16 12:23:28,969] [google-3] INFO  c.s.s.t.g.GoogleTaskRunnable - google thread stopped
[2017-03-16 12:23:34,504] [Thread-11] WARN  c.s.s.t.g.GoogleTask - 50 proxies failed during the task
[2017-03-16 12:23:34,504] [Thread-11] WARN  c.s.s.t.g.GoogleTask - 1170 searches have not been checked`

**Comment by LeFrenchie** [comment]
Again failed this morning with same error "SERVICE_OVERLOADED"

**Comment by zordon32** [comment]
Same here

> [2017-03-17 09:02:04,457] [google-12] ERROR c.s.s.s.g.s.GoogleScraper - solver can't resolve captcha (overload ?) error = SERVICE_OVERLOADED
[2017-03-17 09:02:04,457] [google-12] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.de/search?q=*&num=200 via proxy:http://*:3128/ try 3
[2017-03-17 09:02:05,546] [google-12] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
[2017-03-17 09:02:05,546] [google-12] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:http://*:3128/
[2017-03-17 09:02:06,592] [google-10] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[200] exception=[none]
[2017-03-17 09:02:06,625] [google-10] TRACE c.s.s.s.g.s.GoogleScraper - sleeping 5137 milliseconds
[2017-03-17 09:02:06,950] [google-12] DEBUG c.s.s.s.g.s.GoogleScraper - trying with captcha recaptcha
[2017-03-17 09:02:06,950] [google-12] INFO  c.s.s.s.c.s.FailoverCaptchaSolver - all captcha solver failed
[2017-03-17 09:02:06,950] [google-12] ERROR c.s.s.s.g.s.GoogleScraper - solver can't resolve captcha (overload ?) error = SERVICE_OVERLOADED
[2017-03-17 09:02:06,954] [google-12] WARN  c.s.s.t.g.GoogleTaskRunnable - scrap failed for * because of ERROR_CAPTCHA_INCORRECT
[2017-03-17 09:02:06,954] [google-12] WARN  c.s.s.t.g.GoogleTaskRunnable - no more proxy, stopping the thread
[2017-03-17 09:02:06,955] [google-12] INFO  c.s.s.t.g.GoogleTaskRunnable - google thread stopped
[2017-03-17 09:02:11,799] [google-10] INFO  c.s.s.t.g.GoogleTaskRunnable - search "*" | try 1 | total search done : 866/1141
[2017-03-17 09:02:11,799] [google-10] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.de/search?q=*&num=200 via proxy:http://*:3128/ try 1
[2017-03-17 09:02:12,822] [google-10] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
[2017-03-17 09:02:12,822] [google-10] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:http://*:3128/
[2017-03-17 09:02:14,546] [google-10] DEBUG c.s.s.s.g.s.GoogleScraper - trying with captcha recaptcha
[2017-03-17 09:02:14,546] [google-10] INFO  c.s.s.s.c.s.FailoverCaptchaSolver - all captcha solver failed
[2017-03-17 09:02:14,546] [google-10] ERROR c.s.s.s.g.s.GoogleScraper - solver can't resolve captcha (overload ?) error = SERVICE_OVERLOADED
[2017-03-17 09:02:14,546] [google-10] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.de/search?q=*&num=200 via proxy:http://*:3128/ try 2
[2017-03-17 09:02:16,128] [google-10] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
[2017-03-17 09:02:16,129] [google-10] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:http://*:3128/
[2017-03-17 09:02:16,865] [google-10] DEBUG c.s.s.s.g.s.GoogleScraper - trying with captcha recaptcha
[2017-03-17 09:02:16,866] [google-10] INFO  c.s.s.s.c.s.FailoverCaptchaSolver - all captcha solver failed
[2017-03-17 09:02:16,866] [google-10] ERROR c.s.s.s.g.s.GoogleScraper - solver can't resolve captcha (overload ?) error = SERVICE_OVERLOADED
[2017-03-17 09:02:16,866] [google-10] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.de/search?q=*&num=200 via proxy:http://*:3128/ try 3
[2017-03-17 09:02:17,929] [google-11] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[200] exception=[none]
[2017-03-17 09:02:17,953] [google-11] TRACE c.s.s.s.g.s.GoogleScraper - sleeping 5270 milliseconds
[2017-03-17 09:02:18,272] [google-10] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
[2017-03-17 09:02:18,272] [google-10] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:http://*:3128/
[2017-03-17 09:02:19,009] [google-10] DEBUG c.s.s.s.g.s.GoogleScraper - trying with captcha recaptcha
[2017-03-17 09:02:19,009] [google-10] INFO  c.s.s.s.c.s.FailoverCaptchaSolver - all captcha solver failed
[2017-03-17 09:02:19,009] [google-10] ERROR c.s.s.s.g.s.GoogleScraper - solver can't resolve captcha (overload ?) error = SERVICE_OVERLOADED
[2017-03-17 09:02:19,013] [google-10] WARN  c.s.s.t.g.GoogleTaskRunnable - scrap failed for * because of ERROR_CAPTCHA_INCORRECT
[2017-03-17 09:02:19,013] [google-10] WARN  c.s.s.t.g.GoogleTaskRunnable - no more proxy, stopping the thread
[2017-03-17 09:02:19,013] [google-10] INFO  c.s.s.t.g.GoogleTaskRunnable - google thread stopped

**Comment by serphacker** [comment]
I will fix the OVERLOAD issue this week end stay tunned on this thread

**Comment by Cykucjusz** [comment]
@serphacker 
With option Recheck failed/new keywords all works fine. Overload issue is for you a piece of cake. Thank you again.

**Comment by tipmaster** [comment]
Overload issue hits for me after 5 keywords for 350; looking forward to the fix.

**Comment by LeFrenchie** [comment]
Do you some news about fix Pierre ? Thanks

**Comment by serphacker** [comment]
Can you try https://serposcope.serphacker.com/beta/2.7.1/

**Comment by zordon32** [comment]
Installed it and made a test run with 2585 keywords and it worked

**Comment by LeFrenchie** [comment]
Install done, results tomorrow for me

**Comment by tipmaster** [comment]
Issue is resolved for me.

**Comment by serphacker** [comment]
ok 2.7.1 released, thanks to testers.

**Comment by serphacker** [comment]
@LeFrenchie it is a different and very minor error. You can ignore it.

**Comment by sebchop** [comment]
it works, thanks a lot
